#!/bin/zsh
# export FLASK_APP="perch:flask_app"
# export FLASK_APP_ENV="development"
# flask --app perch/flask_app.py run --host localhost --port 8000

FLASK_CONFIG='development' flask run --debug --reload
